version: '3.8'

services:
  ansible:
    build: .
    container_name: cb-ansible
    volumes:
      - .:/ansible
      - ~/.aws:/root/.aws
      - C:/Users:/mnt/users
    working_dir: /ansible
    stdin_open: true
    tty: true
    environment:
      - AWS_PROFILE=default